# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "vector<bool>{ true, true, false };"
email: vectorofbool@gmail.com
description: The creations of a mad(dening) template specialization
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vector-of-bool.github.io" # the base hostname & protocol for your site
# url: "http://localhost:4000"
twitter_username: jekyllrb
github_username:  vector-of-bool

modules_posts_md: |
  Posts in this series:
  - [Part 1: Hello Modules, and Module Units](/2019/03/10/modules-1.html)
  - [Part 2: Export, import, visible, and reachable](/2019/03/31/modules-2.html)
  - [Part 3: Linkage and Fragments](/2019/10/07/modules-3.html)

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# keep_files:
#   - docs

include:
  - _static
  - _images
  - _sources
  - _*.html

image:
  source: assets/images/_fullsize
  presets: {}

digits: [1,2,3,4,5,6]

gems:
  - jekyll-minifier

jekyll-minifier:
  exclude: '*.js'